### ISSUE TITLE
Is 1.20.6 supported?

### ISSUE THREAD

**Issue by Logan8642** [xCykrix/DynamicLights#15]
Is 1.20.6 supported with the latest update?

**Comment by xCykrix** [comment]
@Logan8642 Apologies for the delay. Do you get any errors when loading this with 1.20.6? There is nothing that should prevent it but may need some maintenance updates.

Will look into this over the next two days.

**Comment by xCykrix** [comment]
Released with v1.0.7 on SpigotMC and GitHub.

https://www.spigotmc.org/resources/dynamiclights.110707/
https://github.com/xCykrix/DynamicLights/releases/tag/v1.0.7
