### ISSUE TITLE
add 1.17.1 support/ discord link

### ISSUE THREAD

**Issue by fr3d3lin** [xCykrix/DynamicLights#16]
hello, your discord link dosent work

can you add 1.17.1 support :D 

i like the /dynamiclights toggle

**Comment by xCykrix** [comment]
I'll look into supporting 1.17.x set of versions and fix the discord links as well.

**Comment by fr3d3lin** [comment]
if you want, in exchange, if you put a lang.yml file, I can translate the plugin into French for you.

**Comment by xCykrix** [comment]
Work has been completed and merged to main. Pending release.

**Comment by xCykrix** [comment]
Verified support for v1.17.x has been added in DynamicLights v1.1.0.

https://www.spigotmc.org/resources/dynamiclights.110707/update?update=558010
https://github.com/xCykrix/DynamicLights/releases/tag/v1.1.0

This update has a lot of fundamental changes. Please let me know if you have any issues by creating a new issue for me to track and include any alerts or error messages.

For early versions, the default lights.yml will throw some warnings. You can disregard these as Frog Lights do not exist yet.

```
>version
[11:51:14] [Server thread/INFO]: This server is running CraftBukkit version 3284a-Spigot-3892929-0ab8487 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT)
[11:51:14] [Server thread/INFO]: Checking version, please wait...
[11:51:15] [Thread-11/INFO]: You are 52 version(s) behind
>pl
[11:51:15] [Server thread/INFO]: Plugins (2): ProtocolLib, DynamicLights
```

**Comment by xCykrix** [comment]
@fr3d3lin https://discord.gg/RHJQFPgbke - Discord has been created. It is blank currently but you can feel free to join and interact with any of the channels if you have suggestions or issues.

Still backfilling information and getting everything set up.
