### ISSUE TITLE
ACF Stacktrace 1.20.2

### ISSUE THREAD

**Issue by smhcnshn** [xCykrix/DynamicLights#9]
On Version 1.20.2 ACF gives "Can't read Player Locale" Stacktrace, the plugin still works fine but it would be great to fix this https://mclo.gs/TVzxQ3C

**Comment by xCykrix** [comment]
Work is being done to fix this issue. This is caused upstream by my PluginCommon bundled api.

Reference: https://github.com/xCykrix/PluginCommon/issues/1
